export const UPDATE_PLAYER_STATUS = 'UPDATE_PLAYER_STATUS';
export const ADD_VIDEO = 'ADD_VIDEO';
export const UPDATE_PLAYER_TOTAL_TIME = 'UPDATE_PLAYER_TOTAL_TIME';
export const UPDATE_PLAYER_ELAPSED_TIME = 'UPDATE_PLAYER_ELAPSED_TIME';
export const ADD_STATUS_TYPES = 'ADD_STATUS_TYPES';

export const RETRIEVE_VIDEOS = 'RETRIEVE_VIDEOS';
export const RETRIEVE_VIDEOS_FULFILLED = 'RETRIEVE_VIDEOS_FULFILLED';
export const RETRIEVE_VIDEOS_PENDING = 'RETRIEVE_VIDEOS_PENDING';
export const RETRIEVE_VIDEOS_REJECTED = 'RETRIEVE_VIDEOS_REJECTED';